#! /bin/bash

usage()
{
cat << EOF
usage: $0 options

This script deploys code to the elastic beanstalk environment associated with this git branch.

OPTIONS:
   -h      Show this message
   -u      Update vendors via composer
EOF
}

GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ $GIT_BRANCH =~ production ]]
then
    echo "You're about to deploy from a production git branch: $GIT_BRANCH are you sure? (yes/no)"
    read CONFIRMATION
    if [[ $CONFIRMATION =~ n ]]
    then
        echo "Deployment cancelled."
        exit
    fi
fi


composer install
COMPOSER_STATUS=$?

if [[ $COMPOSER_STATUS -gt 0 ]]
then
    php composer.phar install
    COMPOSER_STATUS=$?
    if [[ $COMPOSER_STATUS -gt 0 ]]
    then
        echo "Unable to update vendors. Make sure one of 'composer install' or 'php composer.phar install' works."
        exit
    fi
fi

echo "Beginning PHPUnit testing."
PHPUNIT_OUTPUT=$(bin/phpunit -c app)
PHPUNIT_STATUS=$?

if [[ $PHPUNIT_STATUS -eq 0 ]]
then
    echo "$PHPUNIT_OUTPUT"
    if [[ $PHPUNIT_OUTPUT =~ FAILURES ]]
    then
        echo "PHPUnit testing failed.  Please review the output and try again"
    else
        echo "No PHPUnit failures detected.  Pushing to origin branch $GIT_BRANCH"
        git push origin $GIT_BRANCH
        ORIGIN_PUSH_STATUS=$?
        if [[ $ORIGIN_PUSH_STATUS -eq 0 ]]
        then
            echo "Push to origin branch $GIT_BRANCH successful.  Deploying to Elastic Beanstalk."
            git aws.push
        else
            echo "Unable to push to origin branch $GIT_BRANCH:"
            exit
        fi
    fi
else
    echo "Unable to initialize PHPUnit.  Make sure that 'bin/phpunit -c app' works."
fi