lists_io_home:
    pattern:  /
    defaults: { _controller: ListsIOUserBundle:User:index }

lists_io_tos:
    pattern:  /tos
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    '::tos.html.twig'
    
lists_io_lists:
  resource: "@ListsIOListBundle/Resources/config/routing.yml"
  prefix: /

fos_user_security_login:
    defaults: { _controller: ListsIOUserBundle:Security:login }
    pattern: /user/login

fos_user_security_check:
    pattern: /user/login_check
    defaults: { _controller: ListsIOUserBundle:Security:check }

fos_user_security_logout:
    pattern: /user/logout
    defaults: { _controller: ListsIOUserBundle:Security:logout }

fos_user_register:
    pattern: /register/
    defaults: { _controller: FOSUserBundle:Registration:register }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

fos_user_prefixed_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /user/login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /user/login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /user/login

# !THIS ROUTE MUST GO LAST!  (lowest precedence)
lists_io_user:
  resource: "@ListsIOUserBundle/Resources/config/routing.yml"
  prefix: /