imports:
    - { resource: parameters.yml }
    - { resource: parameters.php }

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /user/login
                use_forward: false
                check_path: /user/login_check
                failure_path: /user/login
                success_handler: listsio.security.component.authentication.handler.login_success_handler
            oauth:
                resource_owners:
                    twitter: "/user/login/check-twitter"
                    facebook: "/login/check-facebook"
                login_path: /user/login
                failure_path: /user/login
                success_handler: listsio.security.component.authentication.handler.login_success_handler
                oauth_user_provider:
                    service: listsio_user_provider

            logout:
                path: /user/logout
            anonymous:    ~
            remember_me:
                key: "%secret%"
                lifetime: 4147200

    access_control:
        # TODO: Require HTTPS for login and register routes.
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login_check$, role; IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role; IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register%, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/view/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/list/\d+, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/list/\w+, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
