imports:
    - { resource: parameters.yml }
    - { resource: parameters.php }

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /user/login
                use_forward: false
                check_path: /user/login_check
                failure_path: /user/login
                success_handler: listsio.security.component.authentication.handler.login_success_handler
            oauth:
                resource_owners:
                    twitter: "/user/login/check-twitter"
                    facebook: "/user/login/check-facebook"
                login_path: /user/login
                failure_path: /user/login
                success_handler: listsio.security.component.authentication.handler.login_success_handler
                oauth_user_provider:
                    service: listsio_user_provider

            logout:
                path: /user/logout
            anonymous:    ~
            remember_me:
                key: "%secret%"
                lifetime: 4147200

    access_control:
        # COMPLETING ACCOUNT REQUIRES LOGIN
        - { path: ^/user/complete_account, roles: ROLE_USER }
        # DELETE, PUT and POST REQUIRE LOGIN
        - { path: ^/.*, roles: ROLE_USER, methods: [DELETE, POST, PUT] }
        # ALL GETS NOT SPECIFIED ABOVE ARE ANONYMOUS
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
