# GET LIST
lists_io_view_list:
    pattern: /list/{id}.{_format}
    requirements:
        id: \d+
        _format: html|json
    methods: [GET]
    defaults:  { _controller: ListsIOListBundle:API:viewList, _format: html }
# EDIT LIST
lists_io_edit_list:
    pattern: /list/{id}/edit
    requirements:
        id: \d+
        _format: html
    methods: [GET]
    defaults:  { _controller: ListsIOListBundle:Page:editList, _format: html }
# NEW LIST
lists_io_edit_new_list:
    pattern: /list/new
    methods: [GET]
    defaults: { _controller: ListsIOListBundle:Page:newList, _format: html }
# POST LIST
lists_io_new_list:
    pattern: /list
    requirements:
        _format: json
    methods: [POST]
    defaults:  { _controller: ListsIOListBundle:API:newList, _format: json }
# POSTLIST ITEM
lists_io_new_list_item:
    pattern: /list_item
    requirements:
        _format: json
    defaults: { _controller: ListsIOListBundle:API:newListItem, _format: json }
    methods: [POST]
# POST LIST
lists_io_save_list:
    pattern: /list/{id}
    requirements:
        userId: \d+
        _format: json
    methods: [PUT]
    defaults: { _controller: ListsIOListBundle:API:saveList, _format: json }
# POST LIST ITEM
lists_io_save_list_item:
    pattern: /list_item/{itemId}
    requirements:
        itemId: \d+
        _format: json
    methods: [PUT]
    defaults: { _controller: ListsIOListBundle:API:saveListItem, _format: json }
# DELETE LIST
lists_io_remove_list:
    pattern: /list/{listId}
    requirements:
        listId: \d+
        _format: json
    methods: [DELETE]
    defaults: { _controller: ListsIOListBundle:API:removeList, _format: json }
# DELETE LIST ITEM
lists_io_remove_list_item:
    pattern: /list_item/{itemId}
    requirements:
        itemId: \d+
        _format: json
    defaults: { _controller: ListsIOListBundle:API:removeListItem, _format: json }
# PUT LIST LIKE
lists_io_new_list_like:
    pattern: /list_like
    methods: [POST]
    requirements:
        _format: json
    defaults:  { _controller: ListsIOListBundle:API:newListLike, _format: json }
# GET POPULAR LISTS
lists_io_view_popular_lists:
    pattern: /lists/popular
    methods: [GET]
    defaults: { _controller: ListsIOListBundle:API:viewPopularLists, _format: json }