parameters:
#    lists_io_list.example.class: ListsIO\Bundle\ListBundle\Example

services:
#    lists_io_list.example:
#        class: %lists_io_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
