lists_io_feed_homepage:
    pattern:  /
    defaults: { _controller: ListsIOFeedBundle:Feed:index }
    
lists_io_feed_next:
    pattern:  /next
    requirements:
        _format: json
    defaults: { _controller: ListsIOFeedBundle:Feed:next, _format: json }