#List Views
CREATE TABLE LIOListView (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, list_id INT DEFAULT NULL, createdAt DATETIME NOT NULL, INDEX IDX_4A22E620A76ED395 (user_id), INDEX IDX_4A22E6203DAE168B (list_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE LIOListView ADD CONSTRAINT FK_4A22E620A76ED395 FOREIGN KEY (user_id) REFERENCES User (id);
ALTER TABLE LIOListView ADD CONSTRAINT FK_4A22E6203DAE168B FOREIGN KEY (list_id) REFERENCES LIOList (id);
# List Likes
CREATE TABLE LIOListLike (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, list_id INT DEFAULT NULL, createdAt DATETIME NOT NULL, INDEX IDX_18BC0D1DA76ED395 (user_id), INDEX IDX_18BC0D1D3DAE168B (list_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE LIOListLike ADD CONSTRAINT FK_18BC0D1DA76ED395 FOREIGN KEY (user_id) REFERENCES User (id);
ALTER TABLE LIOListLike ADD CONSTRAINT FK_18BC0D1D3DAE168B FOREIGN KEY (list_id) REFERENCES LIOList (id);