CREATE TABLE Follow (id INT AUTO_INCREMENT NOT NULL, follower_id INT DEFAULT NULL, followed_id INT DEFAULT NULL, INDEX IDX_6F984146AC24F853 (follower_id), INDEX IDX_6F984146D956F010 (followed_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE Follow ADD CONSTRAINT FK_6F984146AC24F853 FOREIGN KEY (follower_id) REFERENCES User (id);
ALTER TABLE Follow ADD CONSTRAINT FK_6F984146D956F010 FOREIGN KEY (followed_id) REFERENCES User (id);
ALTER TABLE Follow ADD createdAt DATETIME NOT NULL, ADD updatedAt DATETIME NOT NULL;