lists_io_user_view_by_id:
    pattern:  /user/{userId}.{_format}
    requirements:
        userId: \d+
        _format: (html|json)
    defaults: { _controller: ListsIOUserBundle:User:viewById, _format: html }
lists_io_user_view_by_username:
    pattern:  /{username}.{_format}
    requirements:
        username: .+
        _format: (html|json)
    defaults: { _controller: ListsIOUserBundle:User:viewByUsername, _format: html }
