parameters:
    listsio_user_provider.class: ListsIO\Bundle\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    listsio_user_provider:
        class: "%listsio_user_provider.class%"
        arguments: [@fos_user.user_manager, {twitter: twitterId, facebook: facebookId}, @validator, @translator, @logger]