lists_io_home:
    pattern:  /
    defaults: { _controller: ListsIOAppBundle:App:index }
lists_io_location_autocomplete:
    pattern: /location_autocomplete
    defaults: { _controller: ListsIOAppBundle:App:locationAutocomplete }