ListsIO\Bundle\UserBundle\Entity\Follow:
    type: entity
    table: Follow
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    manyToOne:
        follower:
            targetEntity: ListsIO\Bundle\UserBundle\Entity\User
            inversedBy: follows
        followed:
            targetEntity: ListsIO\Bundle\UserBundle\Entity\User
            inversedBy: followedBy
    lifecycleCallbacks:
        prePersist: [prePersistTimestamp]
        preUpdate: [prePersistTimestamp]
