ListsIO\Bundle\UserBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        twitterId:
            type: string
            length: 255
            nullable: true
        twitterUsername:
            type: string
            length: 255
            nullable: true
        twitterAccessToken:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    oneToMany:
        lists:
            targetEntity: ListsIO\Bundle\ListBundle\Entity\LIOList
            mappedBy: user
            cascade: ["remove", "persist"]
    lifecycleCallbacks:
            prePersist: [prePersistTimestamp]
            preUpdate: [prePersistTimestamp]
