ListsIO\Bundle\UserBundle\Entity\User:
    type: entity
    table: User
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    attributeOverride:
        emailCanonical:
            column: email_canonical
            type: string
            length: 255
            unique: false
    fields:
        twitterId:
            type: string
            length: 255
            nullable: true
        twitterUsername:
            type: string
            length: 255
            nullable: true
        twitterAccessToken:
            type: string
            length: 255
            nullable: true
        facebookId:
            type: string
            length: 255
            nullable: true
        facebookUsername:
            type: string
            length: 255
            nullable: true
        facebookAccessToken:
            type: string
            length: 255
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    oneToMany:
        lists:
            targetEntity: ListsIO\Bundle\ListBundle\Entity\LIOList
            orderBy:
              createdAt: DESC
            mappedBy: user
            cascade: ["remove", "persist"]
        listViews:
            targetEntity: ListsIO\Bundle\ListBundle\Entity\LIOListView
            mappedBy: user
            cascade: ["remove"]
        listLikes:
            targetEntity: ListsIO\Bundle\ListBundle\Entity\LIOListLike
            mappedBy: user
            cascade: ["remove"]
    lifecycleCallbacks:
        prePersist: [prePersistTimestamp]
        preUpdate: [prePersistTimestamp]
