lists_io_search_homepage:
    pattern:  /
    defaults: { _controller: ListsIOSearchBundle:Search:index }

lists_io_search_find:
    pattern:  /query
    defaults: { _controller: ListsIOSearchBundle:Search:query }