parameters:
#    lists_io_search.example.class: ListsIO\Bundle\SearchBundle\Example

services:
#    lists_io_search.example:
#        class: %lists_io_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
