ListsIO\Bundle\ListBundle\Entity\LIOListLike:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
    manyToOne:
        user:
            targetEntity: ListsIO\Bundle\UserBundle\Entity\User
            inversedBy: listLikes
        list:
            targetEntity: ListsIO\Bundle\ListBundle\Entity\LIOList
            inversedBy: listLikes
    llifecycleCallbacks:
         prePersist: [prePersistTimestamp]
