ListsIO\Bundle\ListBundle\Entity\LIOList:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        subtitle:
            type: string
            length: 255
        imageURL:
            type: string
            length: 255
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    manyToOne:
        user:
          targetEntity: ListsIO\Bundle\UserBundle\Entity\User
          inversedBy: lists
    oneToMany:
        listItems:
            targetEntity: ListsIO\Bundle\ListBundle\Entity\LIOListItem
            mappedBy: list
            orderBy: { 'orderIndex': 'ASC' }
            cascade: ["remove", "persist"]
        listViews:
            targetEntity: ListsIO\Bundle\ListBundle\Entity\LIOListView
            mappedBy: list
            cascade: ["remove"]
    lifecycleCallbacks:
        prePersist: [prePersistTimestamp]
        preUpdate: [prePersistTimestamp]
